services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    volumes:
      - maxim_ml_database:/app/DataBase/db
      - maxim_ml_models:/app/models

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    depends_on:
      - backend
    ports:
      - "8080:80"

volumes:
  maxim_ml_database:
  maxim_ml_models:
